
spring:
  # 静态资源处理
  resources:
    # 启动默认静态资源处理，默认机制
    cache:
      cachecontrol:
        # 缓存相应时间，单位秒
        max-age: 3600
    add-mappings: true
    chain:
      # 资源链启动缓存，默认启动
      cache: true
      # 启用资源链，默认禁用
      enabled: true
      # 启用压缩资源（gzip，brotil）解析，默认禁用
      compressed: true
      # 启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/
  # thymeleaf??
  thymeleaf:
    # ????
    cache: false
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicaode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lyy18281235812
    hikari:
      # ????
      pool-name: DateHikariCP
      # ???????
      minimum-idle: 5
      # ??????????????10???
      idle-timeout: 180000
      # ????????10
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ?????????0??????????30???
      max-lifetime: 18000000
      # ??????????30??
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1

  # redis配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认魏8
        max-active: 8
        # 最大空闲连接，默认8
        max-idle: 200
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最小空闲连接，默认0
        min-idle: 5
  rabbitmq:
    # 服务器
    host: 127.0.0.1
    # 用户名
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认true
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true
    # 模版方式
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试时间，默认1000ms
        initial-interval: 1000ms
        # 重试最大次数，默认3次
        max-attempts: 3
        # 重试最大间隔时间，默认1000ms
        max-interval: 1000ms
        # 重试的间隔乘数，比如配2.0，第一次就等10s，第二次就等20s，第三次就等40s
        multiplier: 1
# Mybatis-puls??
mybatis-plus:
  # ??Mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ??MyBatis?????????????????
  type-aliases-package: com.monica.seckilldemo.pojo

# MyBatis SQL??????????????Mapper.xml?????
logging:
  level:
    com.xxx.seckill.mapper: debug
